import { Router } from "express";
import { CategoryController } from "../controllers/category.controller";

const router = Router();

/**
 * @swagger
 * components:
 *  schemas:
 *    Category:
 *      type: object
 *      properties:
 *        id:
 *          type: number
 *          description: Autogenerated Id
 *        name:
 *          type: string
 *          description: Name of category
 *        products:
 *          type: array
 *          description: It is a list of products
 *      required:
 *        - id
 *      example:
 *        id: 1
 *        name: category name
 *        products: []
 */

/**
 * @swagger
 * tags:
 *  name: Category
 *  description: endpoints for categories
 */

router.post("/categorires", CategoryController.createCategory);

router.get("/category/:id", CategoryController.getCategory);

/**
 * @swagger
 * /api/categories:
 *  get:
 *    summary: this endpoint get a list of categories
 *    tags: [Category]
 *    responses:
 *      200:
 *        description: the list of categories
 *        content:
 *          application/json:
 *            type: array
 *            items:
 *              $ref: '#/components/schemas/Category'
 */
router.get("/categories", CategoryController.getCategories);

router.delete("/category/:id", CategoryController.deleteCategory);

router.put("/category/:id", CategoryController.updateCategory);

export default router;
