import { Router } from "express";
import { ProductController } from "../controllers/product.controller";

const router = Router();

/**
 * @swagger
 * components:
 *  schemas:
 *    Product:
 *      type: object
 *      properties:
 *        id:
 *          type: number
 *          description: Autogenerated Id
 *        name:
 *          type: string
 *          description: Name of category
 *      required:
 *        - id
 *      example:
 *        id: 1
 *        name: product name
 *  parameters:
 *    productId:
 *      in: path
 *      name: id
 *      required: true
 *      schema;
 *        type: string
 *      description: this is a product ID
 */

/**
 * @swagger
 * tags:
 *  name: Product
 *  description: endpoints for products
 */

/**
 * @swagger
 * /api/products:
 *  post:
 *    summary: create a new product
 *    tags: [Product]
 *    requestBody:
 *      required: true
 *      content:
 *        application/json:
 *          schema:
 *            $ref: '#/components/schemas/Product'
 *    responses:
 *      200:
 *        description: return the product successfully created
 *        content:
 *          application/json:
 *            schema:
 *              $ref: '#/components/schemas/Product'
 *      500:
 *        description: some server error
 *
 */
router.post("/products", ProductController.createProduct);

/**
 * @swagger
 * /api/product/{id}:
 *  get:
 *    summary: obtain a product by ID
 *    tags: [Product]
 *    parameters:
 *      - $ref: '#/components/parameters/productId'
 *    responses:
 *      200:
 *        description: return the product successfully created
 *        content:
 *          application/json:
 *            schema:
 *              $ref: '#/components/schemas/Product'
 *      404:
 *        description: some server error
 *
 */
router.get("/product/:id", ProductController.getProduct);

/**
 * @swagger
 * /api/products:
 *  get:
 *    summary: this endpoint get a list of products
 *    tags: [Product]
 *    responses:
 *      200:
 *        description: the list of products bla bla bla
 *        content:
 *          application/json:
 *            type: array
 *            items:
 *
 */
router.get("/products", ProductController.getProducts);

router.delete("/product/:id", ProductController.deleteProduct);

router.put("/product/:id", ProductController.updateProduct);

export default router;
